# Site settings
title: Data Science Africa
location: Arusha, Tanzania
year: 2017
email: info@datascienceafrica.org
banner: "arusha.jpg"
description: > # this means to ignore newlines until "baseurl:"
  The 2016 Data Science Africa summer school held at Makerere University.
baseurl: "/dsa2017" # the subpath of your site, e.g. /blog/
url: "http://www.datascienceafrica.org" # the base hostname & protocol for your site
twitter_username: datsciAfrica
logo_url: img/logo.png
github_username:  datsciafrica

previous:
  url: /dsa2016/
  text: | # From here to "school:"
    <div class="" style="
                        font-weight: bold; 
                        font-size: 18px;

                        ">Previous: Data Science Africa 2016</div>
    <div>June 27<sup>th</sup>  - July 1<sup>st</sup> 2016</div>
    <div>Kampala, Uganda</div>


social:
  title: Social Event
  text:
  
school:  
  name: Data Science in Africa School
  shortname: DSA2017
  location: "Nelson Mandela African Institute of Science and Technology, Tanzania"
  googleformid: Sq9P9uKrkG1K1f6W2
  dates:		
  - 2017-07-17
  - 2017-07-18
  - 2017-07-19
  registration:
    deadline: 2017-06-26
    open: True
  draft: Y # set to Y if the programme is draft only.
  roles:
  - {type: Organizer, name: Ernest Mwebaze, url: "http://air.ug/~emwebaze"}
  - {type: Organizer, name: Mubangizi Martin Gordon, url: "http://air.ug/~mmubangizi"}
  - {type: Organizer, name: John Quinn, url: "http://air.ug/~jquinn"}
  - {type: Speaker, name: Mike Croucher, url: "http://www.walkingrandomly.com"}
  - {type: Speaker, name: Mike Smith, url: "http://www.michaeltsmith.org"}

conference:
  shortname: DSA2017
  theme: 
  hosts:
  roles:
  - {type: General Chair, name: Dina Machuve, url: "http://www.nm-aist.ac.tz",email: "dina.machuve@nm-aist.ac.tz"}
  - {type: Program Chair, name: Ciira Maina, url: "https://sites.google.com/site/cwamainadekut/", email: "ciira.maina@dkut.ac.ke"}
  name: Data Science in Africa Workshop 
  location: Nelson Mandela African Institute of Science and Technology, Tanzania
  googleformid: Sq9P9uKrkG1K1f6W2
  year: 2017	
  month: July
  registration:
    deadline: 2017-06-26
    open: True
  # add other days here for them to appear
    abstract: 2017-05-26
  dates:	
  - 2017-07-20
  - 2017-07-21
  draft: Y # set to Y if the programme is draft only.
  organizers:
  - {logo: AI.png, name: "AI Research, Makerere University"}
  - {logo: sheffield.png, name: University of Sheffield}
  - {logo: makerere.png, name: Makerere University}
  - {logo: plklogo.png, name: Pulse Lab Kampala}
  - {logo: un_uganda1.png, name: United Nations Uganda}
  - {logo: dedan_kimathi.png, name: Dedan Kimathi University of Technology}
  - {logo: nmaist-logo.png, name: Nelson Mandela African Institute of Science and Technology}
  goldsponsors: 
  #- {logo: facebook.png, name: "Facebook"}  
  #- {logo: google.png, name: "Google"}
  - {logo: HDS_Logo.png, name: "Swansea University", url: "http://www.swansea.ac.uk/mschealthdatascience"}
  - {logo: HI_Logo.png, name: "Swansea University", url: "http://www.mschealthinformatics.swansea.ac.uk"}
  silversponsors:
  - {logo: twas.png, name: "The World Academy of Sciences (TWAS)", url: "http://twas.org/"}
  
feedback: 




exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

sass:
    sass_dir: _scss

# Build settings
markdown: kramdown


analytics:
  google:
    tracking_id: UA-80484960-1

video:
  height: 315
  width: 560

future: true
